rng:
  image: addteq/dockercoins-rng:$IMAGE_TAG
hasher:
  image: addteq/dockercoins-hasher:$IMAGE_TAG
webui:
  image: addteq/dockercoins-webui:$IMAGE_TAG
  ports:
  - 8000:80/tcp
  links:
  - redis:redis
redis:
  image: redis
worker:
  image: addteq/dockercoins-worker:$IMAGE_TAG
  links:
  - redis:redis
  - rng:rng
  - hasher:hasher
