version: '2'
services:
  webui:
    image: addteq/dockercoins-webui
    links:
    - redis:redis
    ports:
    - 8000:80/tcp
  rng:
    image: addteq/dockercoins-rng
  worker:
    image: addteq/dockercoins-worker
    links:
    - rng:rng
    - hasher:hasher
    - redis:redis
  redis:
    image: redis
  hasher:
    image: addteq/dockercoins-hasher
    labels:
      io.rancher.container.pull_image: always
